name: Release

on:
  push:
    branches:
      - release
      - release-* # * implies any branch starting with `release-` for prelease versions

permissions:
  contents: write # Required for github releases
  id-token: write # Required for OIDC authentication

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          version: latest
          run_install: true
      - run: ./release-it.sh # Instead, run `pnx @firefoxic/release-it` in your action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for github releases
